export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const GET_BOOKS = 'getbooks'
export const INPUT_HANDLER = 'inputHandler'
export const AUTO_LOGIN = 'autoLogin'
export const SIGN_UP = 'signup'
export const SEARCH_BOOKS = 'search'
